import { useMemo } from "react";
import { useParams, Navigate } from "react-router-dom";
import { format } from "date-fns";
import { BarChart2, Lock } from "lucide-react";

import { decodeShareToken, REPORT_TABS } from "@/hooks/useReportFilters";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import { OverviewTab }   from "@/components/reports/tabs/OverviewTab";
import { LocationsTab }  from "@/components/reports/tabs/LocationsTab";
import { UsersTab }      from "@/components/reports/tabs/UsersTab";
import { RevenueTab }    from "@/components/reports/tabs/RevenueTab";
import { TrendsTab }     from "@/components/reports/tabs/TrendsTab";

const PublicReportPage = () => {
  const { token } = useParams<{ token: string }>();

  const filters = useMemo(() => {
    if (!token) return null;
    return decodeShareToken(token);
  }, [token]);

  if (!filters) return <Navigate to="/signin" replace />;

  const locationLabel =
    filters.location === "all"
      ? "All Locations"
      : filters.location.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

  return (
    <div className="min-h-screen bg-background">
      {/* Branded header */}
      <header className="border-b border-border bg-white sticky top-0 z-10">
        <div className="mx-auto max-w-5xl px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary">
              <BarChart2 className="h-5 w-5 text-white" />
            </div>
            <span className="text-lg font-bold text-primary">Pakam</span>
          </div>
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Lock className="h-3.5 w-3.5" />
            Read-only shared report
          </div>
        </div>
      </header>

      {/* Report body */}
      <main className="mx-auto max-w-5xl px-6 py-8 space-y-6">
        {/* Title + period */}
        <div>
          <h1 className="text-2xl font-bold text-foreground">Performance Report</h1>
          <div className="mt-2 flex flex-wrap items-center gap-2">
            <span className="inline-flex items-center rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
              {format(filters.from, "MMM d, yyyy")} – {format(filters.to, "MMM d, yyyy")}
            </span>
            <span className="inline-flex items-center rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground">
              {locationLabel}
            </span>
          </div>
        </div>

        {/* Tabs — default to the tab active when shared */}
        <Tabs defaultValue={filters.activeTab} className="space-y-6">
          <TabsList className="h-10 bg-muted/50 border border-border rounded-xl p-1 flex-wrap gap-1">
            {REPORT_TABS.map((tab) => (
              <TabsTrigger
                key={tab.value}
                value={tab.value}
                className="rounded-lg px-4 text-sm data-[state=active]:bg-white data-[state=active]:text-primary data-[state=active]:shadow-sm data-[state=active]:font-semibold"
              >
                {tab.label}
              </TabsTrigger>
            ))}
          </TabsList>

          <TabsContent value="overview"  className="mt-0 focus-visible:outline-none">
            <OverviewTab  filters={filters} />
          </TabsContent>
          <TabsContent value="locations" className="mt-0 focus-visible:outline-none">
            <LocationsTab filters={filters} />
          </TabsContent>
          <TabsContent value="users"     className="mt-0 focus-visible:outline-none">
            <UsersTab     filters={filters} />
          </TabsContent>
          <TabsContent value="revenue"   className="mt-0 focus-visible:outline-none">
            <RevenueTab   filters={filters} />
          </TabsContent>
          <TabsContent value="trends"    className="mt-0 focus-visible:outline-none">
            <TrendsTab    filters={filters} />
          </TabsContent>
        </Tabs>

        {/* Footer */}
        <div className="pt-6 border-t border-border text-center text-xs text-muted-foreground space-y-1">
          <p>
            Generated by{" "}
            <span className="font-semibold text-primary">Pakam</span> · Waste Management Intelligence Platform
          </p>
          <p>This is a shared read-only snapshot. Data may be anonymised.</p>
        </div>
      </main>
    </div>
  );
};

export default PublicReportPage;
